law-search:
  url: https://api.lawnet.vn/Document/Search
  method: POST
  params:
    keyword: null
    lan: 1 # language 1 is VN, 2 is EN
    token: 0=pZek9EUTBNRGszTnpneU5qWXlNRFl5Tm4xN05ETTFOVFkwTVgxN01IMDZX
    secretkey: ==pRek5UVTJOREZkVzNSMVlXNTBiM1IwYVYxYk1GMWJNakF5TkM4d01pOHlNU0F3Tnpvek5qb3lNbDFiT1RNeU5EZzVRVFl0TWpVelJTMDBPVVV5TFRoQ1FrSXRORFkxTkVFeU1ERTFOVVEyWFE9PQV3
  headers:
    Content-Type: application/json
  body:
    page: 1
    keyword: null
    lan: 1
    match: false
    matchTemp: false
    type: -1
    field: 22 # giao thong van tai
    status: 
    bday: 21/02/1944
    eday: 21/02/2024

law-status:
  url: https://api.thuvienphapluat.com//LawStatus/AllLawStatus
  method: POST
  params:
    token: 0=pZek9EUTBNRGszTnpneU5qWXlNRFl5Tm4xN05ETTFOVFkwTVgxN01IMDZX

law-organization:
  url: https://api.thuvienphapluat.com//Organ/AllOrgan
  method: POST
  params:
    token: 0=pZek9EUTBNRGszTnpneU5qWXlNRFl5Tm4xN05ETTFOVFkwTVgxN01IMDZX

law-detail:
  url: https://api.lawnet.vn/document-detail
  method: GET
  params:
    secretkey: 0=pCZFcxMWJNRjFiTWpBeU5DOHdNaTh5TVNBeE5qb3lNem93TlYxYk9UTXlORGc1UVRZdE1qVXpSUzAwT1VVeUxUaENRa0l0TkRZMU5FRXlNREUxTlVRMlhRPTV3
    LawID: 599102
    language: VN

list-question-by-lawid:
  url: https://lawnet.vn/ngan-hang-phap-luat/ApiNHCH/GetListCauHoiByIdVanBan
  method: GET
  params:
    lawId: 599102
    type: 1 # 1 or 2

suggest-by-law:
  url: https://api.lawnet.vn/GetByLawID
  method: GET
  params:
    LawID: 82203
    language: VN
